### ISSUE TITLE
Startup script does not work when running on Parallel Server from Production Server

### ISSUE THREAD

**Issue by jessehl** [mathworks-ref-arch/matlab-azure-blob#2]
Hi there!

This library works fine on Matlab Production Server (MPS). It also works fine when we run the library on Matlab Parallel Server _from Matlab Desktop_. **However, when our MPS-deployed code invokes Matlab Parallel Server, we face some issues**. In particular, the [`startup`](https://github.com/mathworks-ref-arch/matlab-azure-blob/blob/master/Software/MATLAB/startup.m) script assumes that the `lib`, `app`, and `config` folders exist on the Parallel Server worker(s). However, when _MPS_ sends the files to the Parallel Server worker(s), the file structure looks like this (we've obtained this info by calling `dir('../**')` on code inside a Parallel Server `parfor`):
- `app\functions` can be found in: `matlab\filedependencies\46\a\tpc9d40274_d272_490e_895e_80f2ed2fece4\app\functions`
- `app\system\+azure` can be found in: `matlab\filedependencies\46\a\tp8c1f330a_6302_48a1_bfd2_cc0f21fd6672\+azure`. 
- `lib/*.jar` can be found in `matlab\filedependencies\46\a\tpe4405576_c877_44d7_81cd_7c2c58b75a97\azure-wasb-sdk-0.1.0.jar`

By default, the startup script doesn't recognize any of these folders because they all get their own 'random' names (e.g. `tpc9d4 ... `). The result is:
```matlab
MATLABException: This package doesn't contain the required jar file.
```

I've managed to include the jar by setting `jarFiles = dir(fullfile(here, '..', '**', 'azure-wasb-sdk-0.1.0.jar'))` in the startup script. However, I still struggle to include the correct Matlab (`.m`) code:
```matlab
15653 [2021.09.30 09:21:28.964851] [err] [worker:747] {Error using azure.storage.blob/CloudBlobClient (line 38)
15654 [2021.09.30 09:21:28.964851] [err] [worker:747] Unrecognized method, property, or field 'setDirectoryDelimiter' for class 'azure.storage.blob.CloudBlobClient'.
```

I've found that modifying the startup script to include the Matlab code is challenging:
- The structure and naming of the folders is not consistent (i.e. different when running on Desktop / MPS / MJS) and random (e.g. `tp8c1f330a... `)
- We simply can't add the `+azure` folder (right?), because that results in: `Warning: Package directories not allowed in MATLAB path: C:\ProgramData\MJS\Checkpoint\<hostname>_worker01_mlworker_log\matlab\filedependencies\46\a\tp8c1f330a_6302_48a1_bfd2_cc0f21fd6672\+azure`. 

**Has anyone solved the problem of modifying the startup script, _such that it works when MPS-deployed code uses Matlab Parallel Server_?** Are there any other things we can try? 

## Notes
We sent the necessary files to Matlab Parallel Server using:
```matlab
parpool('DEV', 2, 'IdleTimeout', 1, 'AttachedFiles', {'matlab-azure-blob/matlab-azure-blob/SOFTWARE'});
```

## Environment and Versions
- Matlab Desktop and Parallel Server: R2020B 
- Matlab Production Server: R2021A
- Windows (Azure) VMs

Thanks!

**Comment by jessehl** [comment]
## Update

I've tried to modify the `startup` script. All required folders seem to get added to path:
```log
16895 [2021.11.25 12:44:17.941125] [out] [worker:656] Adding Azure WASB Paths
16896 [2021.11.25 12:44:17.941125] [out] [worker:656] -----------------------
16897 [2021.11.25 12:44:17.941125] [out] [worker:656] Adding C:\ProgramData\MJS\Checkpoint\<redacted>_worker01_mlworker_log\matlab\filedependencies\16\a\tp0fab2269_ce73_4cfc_9b46_032baf2778e1
16898 [2021.11.25 12:44:17.941125] [out] [worker:656] Adding C:\ProgramData\MJS\Checkpoint\<redacted>_worker01_mlworker_log\matlab\filedependencies\16\a\tp78c6f4cc_a00e_496f_a760_59b519026681
16899 [2021.11.25 12:44:17.941125] [out] [worker:656] Adding C:\ProgramData\MJS\Checkpoint\<redacted>_worker01_mlworker_log\matlab\filedependencies\16\a\tp85901396_aa4c_4e35_b46b_b5f0d31af36c\app\functions
16900 [2021.11.25 12:44:17.941125] [out] [worker:656] Adding C:\ProgramData\MJS\Checkpoint\<redacted>_worker01_mlworker_log\matlab\filedependencies\16\a\tp85901396_aa4c_4e35_b46b_b5f0d31af36c\app\system
16901 [2021.11.25 12:44:17.941125] [out] [worker:656] Adding C:\ProgramData\MJS\Checkpoint\<redacted>_worker01_mlworker_log\matlab\filedependencies\16\a\tp85901396_aa4c_4e35_b46b_b5f0d31af36c\lib\jar
16902 [2021.11.25 12:44:17.941125] [out] [worker:656] Adding C:\ProgramData\MJS\Checkpoint\<redacted>_worker01_mlworker_log\matlab\filedependencies\16\a\tp9b8a49f6_b00a_4440_9c10_f589ff1ffd9d
```

Unfortunately, even though the paths get added, I get this error:
```
16913 [2021.11.25 12:44:17.966077] [err] [worker:656] {Error using getAzContainer (line 27)
16914 [2021.11.25 12:44:17.966077] [err] [worker:656] Previously accessible file
16915 [2021.11.25 12:44:17.966077] [err] [worker:656] "C:\ProgramData\MJS\Checkpoint\<redacted>_worker01_mlworker_log\matlab\filedependencies\16\a\tp85901396_aa4c_4e35_b46b_b5f0d31af36c\app\system\+azure\+storage\@StorageUri\StorageUri.m"
16916 [2021.11.25 12:44:17.966077] [err] [worker:656] is now inaccessible.
16917 [2021.11.25 12:44:17.966077] [err] [worker:656] 
16918 [2021.11.25 12:44:17.966077] [err] [worker:656] Error in blob_storage_test (line 44)
16919 [2021.11.25 12:44:17.966077] [err] [worker:656] 
16920 [2021.11.25 12:44:17.966077] [err] [worker:656] Error in sample_model (line 28)
16921 [2021.11.25 12:44:17.966077] [err] [worker:656] } 
```

Based on [this answer](https://nl.mathworks.com/matlabcentral/answers/337667-previously-accessible-file-is-now-inaccessible), I've tried to call `rehash toolboxcache;` _before_ calling the library. However, that doesn't work, either 😮:
```matlab
[err] [worker:4110] {Error using sample_model (line 28)
[err] [worker:4110] foundation::storage::vfs::InvalidIRIException
[err] [worker:4110] } 
```
I get the same result when running this piece of code _from Matlab Desktop_.

**Comment by brownemi** [comment]
Hi Jessehl,

Apologies for the delay in responding, for some reason no notification was received for the initial issue, only your subsequent follow up message today. The package can be used with Parallel Server and Production Server and I don't immediately see what this issue might be, especially given that it behaves the same when called from Desktop MATLAB. Given this more complex use case can I suggest that you email mwlab@mathworks.com to arrange a call to look at the issue.

**Comment by jessehl** [comment]
Hi @brownemi ,

No problem. Will do!

In the meantime I _seem_ to have noticed that not all `AttachedFiles` (in particular `@StorageUri\StorageUri.m`) seem to end up on the MJS worker. I'll collect a bit more info from my end before initiating the call. 

**[Edit, 2021-12-01]**

After running some more tests, I've found that all `AttachedFiles` **do** end up on the MJS worker (that includes `@StorageUri\StorageUri."`). I'll contact mwlab@mathworks.com.

**Comment by jessehl** [comment]
## Closing issue

Our motivation to use this library was to be able to read/write .mat files from/to Blob Storage (preferrably using a simple `save` / `load` function).

@brownemi has informed me that, with our version of Matlab (2020b), we can simply use Matlab's native `copyfile` to move (`.mat`) files/to from Blob Storage. So for us, there is no need to use this library after all. 

I was informed by @brownemi that `save` and `load`  in later version of Matlab will support Azure Blob Storage natively. Right now, we still need to write (delete) temporary files before (after) calling `copyfile`. That's not ideal, but at the same time that's also what happens internally when calling `azContainer.save` of this library. So for us it's a big win that we can use something that is natively supported ( `copyfile`).

**Comment by brownemi** [comment]
Glad we were able to resolve this in a simpler way. `movefile` https://www.mathworks.com/help/matlab/ref/movefile.html will do the clean up of the local file for you and is otherwise very similar to `copyfile`.
